/********************************************************************
* LandauGaussDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LandauGaussDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableLandauGaussDict();
extern void G__cpp_setup_inheritanceLandauGaussDict();
extern void G__cpp_setup_typetableLandauGaussDict();
extern void G__cpp_setup_memvarLandauGaussDict();
extern void G__cpp_setup_globalLandauGaussDict();
extern void G__cpp_setup_memfuncLandauGaussDict();
extern void G__cpp_setup_funcLandauGaussDict();
extern void G__set_cpp_environmentLandauGaussDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LandauGauss.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LandauGaussDictLN_TClass;
extern G__linked_taginfo G__LandauGaussDictLN_TBuffer;
extern G__linked_taginfo G__LandauGaussDictLN_TMemberInspector;
extern G__linked_taginfo G__LandauGaussDictLN_TObject;
extern G__linked_taginfo G__LandauGaussDictLN_TNamed;
extern G__linked_taginfo G__LandauGaussDictLN_RooPrintable;
extern G__linked_taginfo G__LandauGaussDictLN_RooAbsArg;
extern G__linked_taginfo G__LandauGaussDictLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_RooAbsReal;
extern G__linked_taginfo G__LandauGaussDictLN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_RooAbsPdf;
extern G__linked_taginfo G__LandauGaussDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__LandauGaussDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__LandauGaussDictLN_RooRealProxy;
extern G__linked_taginfo G__LandauGaussDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_reverse_iteratorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LandauGaussDictLN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_RooCacheManagerlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_listlERooArgSetmUcOallocatorlERooArgSetmUgRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_LandauGauss;

/* STUB derived class for protected member access */
