//
// File generated by rootcint at Wed Apr 15 14:04:41 2009

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "LandauGaussDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void LandauGauss_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_LandauGauss(void *p = 0);
   static void *newArray_LandauGauss(Long_t size, void *p);
   static void delete_LandauGauss(void *p);
   static void deleteArray_LandauGauss(void *p);
   static void destruct_LandauGauss(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::LandauGauss*)
   {
      ::LandauGauss *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::LandauGauss >(0);
      static ::ROOT::TGenericClassInfo 
         instance("LandauGauss", ::LandauGauss::Class_Version(), "LandauGauss.h", 21,
                  typeid(::LandauGauss), DefineBehavior(ptr, ptr),
                  &::LandauGauss::Dictionary, isa_proxy, 0,
                  sizeof(::LandauGauss) );
      instance.SetNew(&new_LandauGauss);
      instance.SetNewArray(&newArray_LandauGauss);
      instance.SetDelete(&delete_LandauGauss);
      instance.SetDeleteArray(&deleteArray_LandauGauss);
      instance.SetDestructor(&destruct_LandauGauss);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::LandauGauss*)
   {
      return GenerateInitInstanceLocal((::LandauGauss*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::LandauGauss*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *LandauGauss::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *LandauGauss::Class_Name()
{
   return "LandauGauss";
}

//______________________________________________________________________________
const char *LandauGauss::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::LandauGauss*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int LandauGauss::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::LandauGauss*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void LandauGauss::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::LandauGauss*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *LandauGauss::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::LandauGauss*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void LandauGauss::Streamer(TBuffer &R__b)
{
   // Stream an object of class LandauGauss.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      RooAbsPdf::Streamer(R__b);
      x.Streamer(R__b);
      width.Streamer(R__b);
      mp.Streamer(R__b);
      area.Streamer(R__b);
      gSigma.Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, LandauGauss::IsA());
   } else {
      R__c = R__b.WriteVersion(LandauGauss::IsA(), kTRUE);
      RooAbsPdf::Streamer(R__b);
      x.Streamer(R__b);
      width.Streamer(R__b);
      mp.Streamer(R__b);
      area.Streamer(R__b);
      gSigma.Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void LandauGauss::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class LandauGauss.
      TClass *R__cl = ::LandauGauss::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "x", &x);
      x.ShowMembers(R__insp, strcat(R__parent,"x.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "width", &width);
      width.ShowMembers(R__insp, strcat(R__parent,"width.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "mp", &mp);
      mp.ShowMembers(R__insp, strcat(R__parent,"mp.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "area", &area);
      area.ShowMembers(R__insp, strcat(R__parent,"area.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "gSigma", &gSigma);
      gSigma.ShowMembers(R__insp, strcat(R__parent,"gSigma.")); R__parent[R__ncp] = 0;
      RooAbsPdf::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_LandauGauss(void *p) {
      return  p ? new(p) ::LandauGauss : new ::LandauGauss;
   }
   static void *newArray_LandauGauss(Long_t nElements, void *p) {
      return p ? new(p) ::LandauGauss[nElements] : new ::LandauGauss[nElements];
   }
   // Wrapper around operator delete
   static void delete_LandauGauss(void *p) {
      delete ((::LandauGauss*)p);
   }
   static void deleteArray_LandauGauss(void *p) {
      delete [] ((::LandauGauss*)p);
   }
   static void destruct_LandauGauss(void *p) {
      typedef ::LandauGauss current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::LandauGauss

/********************************************************
* LandauGaussDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableLandauGaussDict();

extern "C" void G__set_cpp_environmentLandauGaussDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("LandauGauss.h");
  G__cpp_reset_tagtableLandauGaussDict();
}
#include <new>
extern "C" int G__cpp_dllrevLandauGaussDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* LandauGauss */
static int G__LandauGaussDict_660_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   LandauGauss* p = NULL;
   long gvp = G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new LandauGauss[n];
     } else {
       p = new((void*) gvp) LandauGauss[n];
     }
   } else {
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new LandauGauss;
     } else {
       p = new((void*) gvp) LandauGauss;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_660_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   LandauGauss* p = NULL;
   long gvp = G__getgvp();
   //m: 7
   if ((gvp == G__PVOID) || (gvp == 0)) {
     p = new LandauGauss(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, *(RooAbsReal*) libp->para[2].ref, *(RooAbsReal*) libp->para[3].ref
, *(RooAbsReal*) libp->para[4].ref, *(RooAbsReal*) libp->para[5].ref
, *(RooAbsReal*) libp->para[6].ref);
   } else {
     p = new((void*) gvp) LandauGauss(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, *(RooAbsReal*) libp->para[2].ref, *(RooAbsReal*) libp->para[3].ref
, *(RooAbsReal*) libp->para[4].ref, *(RooAbsReal*) libp->para[5].ref
, *(RooAbsReal*) libp->para[6].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_660_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   LandauGauss* p = NULL;
   long gvp = G__getgvp();
   switch (libp->paran) {
   case 2:
     //m: 2
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new LandauGauss(*(LandauGauss*) libp->para[0].ref, (const char*) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) LandauGauss(*(LandauGauss*) libp->para[0].ref, (const char*) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new LandauGauss(*(LandauGauss*) libp->para[0].ref);
     } else {
       p = new((void*) gvp) LandauGauss(*(LandauGauss*) libp->para[0].ref);
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_660_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) LandauGauss::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_660_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) LandauGauss::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_660_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) LandauGauss::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_660_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      LandauGauss::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_660_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LandauGauss*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_660_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) LandauGauss::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_660_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) LandauGauss::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_660_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) LandauGauss::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_660_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) LandauGauss::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef LandauGauss G__TLandauGauss;
static int G__LandauGaussDict_660_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   long gvp = G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == G__PVOID) {
       delete[] (LandauGauss*) soff;
     } else {
       G__setgvp(G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((LandauGauss*) (soff+(sizeof(LandauGauss)*i)))->~G__TLandauGauss();
       }
       G__setgvp(gvp);
     }
   } else {
     if (gvp == G__PVOID) {
       delete (LandauGauss*) soff;
     } else {
       G__setgvp(G__PVOID);
       ((LandauGauss*) (soff))->~G__TLandauGauss();
       G__setgvp(gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* LandauGauss */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncLandauGaussDict {
 public:
  G__Sizep2memfuncLandauGaussDict(): p(&G__Sizep2memfuncLandauGaussDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncLandauGaussDict::*p)();
};

size_t G__get_sizep2memfuncLandauGaussDict()
{
  G__Sizep2memfuncLandauGaussDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceLandauGaussDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss))) {
     LandauGauss *G__Lderived;
     G__Lderived=(LandauGauss*)0x1000;
     {
       RooAbsPdf *G__Lpbase=(RooAbsPdf*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss),G__get_linked_tagnum(&G__LandauGaussDictLN_RooAbsPdf),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       RooAbsReal *G__Lpbase=(RooAbsReal*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss),G__get_linked_tagnum(&G__LandauGaussDictLN_RooAbsReal),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       RooAbsArg *G__Lpbase=(RooAbsArg*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss),G__get_linked_tagnum(&G__LandauGaussDictLN_RooAbsArg),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss),G__get_linked_tagnum(&G__LandauGaussDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss),G__get_linked_tagnum(&G__LandauGaussDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       RooPrintable *G__Lpbase=(RooPrintable*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss),G__get_linked_tagnum(&G__LandauGaussDictLN_RooPrintable),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableLandauGaussDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("set<std::string>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string,less<string>>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<std::pair<RooAbsArg*,RooAbsArg*> >",117,G__get_linked_tagnum(&G__LandauGaussDictLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<pair<RooAbsArg*,RooAbsArg*>>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<pair<RooAbsArg*,RooAbsArg*>,less<pair<RooAbsArg*,RooAbsArg*> >>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("deque<RooAbsCache*>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,std::string>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,string>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,string,less<int>>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<StreamConfig>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_reverse_iteratorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_reverse_iteratorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<RooMsgService::StreamConfig>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::ostream*>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,basic_ostream<char,char_traits<char> >*>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,basic_ostream<char,char_traits<char> >*,less<string>>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RooCacheManager<std::vector<Double_t> >",117,G__get_linked_tagnum(&G__LandauGaussDictLN_RooCacheManagerlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<RooArgSet*>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_listlERooArgSetmUcOallocatorlERooArgSetmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* LandauGauss */
static void G__setup_memvarLandauGauss(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss));
   { LandauGauss *p; p=(LandauGauss*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LandauGaussDictLN_RooRealProxy),-1,-1,2,"x=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LandauGaussDictLN_RooRealProxy),-1,-1,2,"width=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LandauGaussDictLN_RooRealProxy),-1,-1,2,"mp=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LandauGaussDictLN_RooRealProxy),-1,-1,2,"area=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LandauGaussDictLN_RooRealProxy),-1,-1,2,"gSigma=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__LandauGaussDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarLandauGaussDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncLandauGauss(void) {
   /* LandauGauss */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss));
   G__memfunc_setup("LandauGauss",1112,G__LandauGaussDict_660_0_1, 105, G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LandauGauss",1112,G__LandauGaussDict_660_0_2, 105, G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss), -1, 0, 7, 1, 1, 0, 
"C - - 10 - name C - - 10 - title "
"u 'RooAbsReal' - 1 - _x u 'RooAbsReal' - 1 - _width "
"u 'RooAbsReal' - 1 - _mp u 'RooAbsReal' - 1 - _area "
"u 'RooAbsReal' - 1 - _gSigma", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LandauGauss",1112,G__LandauGaussDict_660_0_3, 105, G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss), -1, 0, 2, 1, 1, 0, 
"u 'LandauGauss' - 11 - other C - - 10 '0' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("clone",529,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__LandauGaussDictLN_TObject), -1, 0, 1, 1, 1, 8, "C - - 10 - newname", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("evaluate",855,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 2, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__LandauGaussDict_660_0_6, 85, G__get_linked_tagnum(&G__LandauGaussDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&LandauGauss::Class), 0);
   G__memfunc_setup("Class_Name",982,G__LandauGaussDict_660_0_7, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&LandauGauss::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__LandauGaussDict_660_0_8, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&LandauGauss::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__LandauGaussDict_660_0_9, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&LandauGauss::Dictionary), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__LandauGaussDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__LandauGaussDict_660_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__LandauGaussDict_660_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&LandauGauss::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__LandauGaussDict_660_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&LandauGauss::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__LandauGaussDict_660_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&LandauGauss::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__LandauGaussDict_660_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&LandauGauss::DeclFileLine), 0);
   // automatic destructor
   G__memfunc_setup("~LandauGauss", 1238, G__LandauGaussDict_660_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncLandauGaussDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalLandauGaussDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcLandauGaussDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__LandauGaussDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_RooPrintable = { "RooPrintable" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_RooAbsArg = { "RooAbsArg" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR = { "set<string,less<string>,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR = { "set<pair<RooAbsArg*,RooAbsArg*>,less<pair<RooAbsArg*,RooAbsArg*> >,allocator<pair<RooAbsArg*,RooAbsArg*> > >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_RooAbsReal = { "RooAbsReal" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR = { "deque<RooAbsCache*,allocator<RooAbsCache*> >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_RooAbsPdf = { "RooAbsPdf" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_RooRealProxy = { "RooRealProxy" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR = { "map<int,string,less<int>,allocator<pair<const int,string> > >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR = { "vector<RooMsgService::StreamConfig,allocator<RooMsgService::StreamConfig> >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_reverse_iteratorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcLcLiteratorgR = { "reverse_iterator<vector<RooMsgService::StreamConfig,allocator<RooMsgService::StreamConfig> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR = { "map<string,basic_ostream<char,char_traits<char> >*,less<string>,allocator<pair<const string,basic_ostream<char,char_traits<char> >*> > >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_RooCacheManagerlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgR = { "RooCacheManager<vector<double,allocator<double> > >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_listlERooArgSetmUcOallocatorlERooArgSetmUgRsPgR = { "list<RooArgSet*,allocator<RooArgSet*> >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_LandauGauss = { "LandauGauss" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableLandauGaussDict() {
  G__LandauGaussDictLN_TClass.tagnum = -1 ;
  G__LandauGaussDictLN_TBuffer.tagnum = -1 ;
  G__LandauGaussDictLN_TMemberInspector.tagnum = -1 ;
  G__LandauGaussDictLN_TObject.tagnum = -1 ;
  G__LandauGaussDictLN_TNamed.tagnum = -1 ;
  G__LandauGaussDictLN_RooPrintable.tagnum = -1 ;
  G__LandauGaussDictLN_RooAbsArg.tagnum = -1 ;
  G__LandauGaussDictLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_RooAbsReal.tagnum = -1 ;
  G__LandauGaussDictLN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_RooAbsPdf.tagnum = -1 ;
  G__LandauGaussDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__LandauGaussDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__LandauGaussDictLN_RooRealProxy.tagnum = -1 ;
  G__LandauGaussDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_reverse_iteratorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LandauGaussDictLN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_RooCacheManagerlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_listlERooArgSetmUcOallocatorlERooArgSetmUgRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_LandauGauss.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableLandauGaussDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_RooPrintable);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_RooAbsArg);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_RooAbsReal);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_RooAbsPdf);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_RooRealProxy);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_reverse_iteratorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_RooCacheManagerlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_listlERooArgSetmUcOallocatorlERooArgSetmUgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__LandauGaussDictLN_LandauGauss),sizeof(LandauGauss),-1,63232,"Your description goes here...",G__setup_memvarLandauGauss,G__setup_memfuncLandauGauss);
}
extern "C" void G__cpp_setupLandauGaussDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupLandauGaussDict()");
  G__set_cpp_environmentLandauGaussDict();
  G__cpp_setup_tagtableLandauGaussDict();

  G__cpp_setup_inheritanceLandauGaussDict();

  G__cpp_setup_typetableLandauGaussDict();

  G__cpp_setup_memvarLandauGaussDict();

  G__cpp_setup_memfuncLandauGaussDict();
  G__cpp_setup_globalLandauGaussDict();
  G__cpp_setup_funcLandauGaussDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncLandauGaussDict();
  return;
}
class G__cpp_setup_initLandauGaussDict {
  public:
    G__cpp_setup_initLandauGaussDict() { G__add_setup_func("LandauGaussDict",(G__incsetup)(&G__cpp_setupLandauGaussDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initLandauGaussDict() { G__remove_setup_func("LandauGaussDict"); }
};
G__cpp_setup_initLandauGaussDict G__cpp_setup_initializerLandauGaussDict;

