<use name=FWCore/Framework>

<library file=stubs/EcalPedHistDumperModule.cc name=EcalPedHistDumperModule>
   <flags EDM_PLUGIN=1>
   <use name=cppunit>
   <use name=root>
   <use name=DataFormats/EcalDigi>
</library> 

<library file=stubs/EcalDigiDumperModule.cc name=EcalDigiDumperModule>
   <flags EDM_PLUGIN=1> 
   <use name=cppunit>
   <use name=DataFormats/EcalDigi>
</library> 

<library file=stubs/EcalDCCHeaderDumperModule.cc name=EcalDCCHeaderDumperModule>
   <flags EDM_PLUGIN=1> 
   <use name=cppunit>
   <use name=DataFormats/EcalRawData>
</library> 

<library file=stubs/EcalHexDumperModule.cc name=EcalHexDumperModule>
   <flags EDM_PLUGIN=1> 
   <use name=cppunit>
   <use name=DataFormats/FEDRawData>
</library> 

<library file=stubs/EcalMatacqHist.cc name=EcalMatacqHist>
   <flags EDM_PLUGIN=1> 
   <use name=cppunit>
   <use name=DataFormats/EcalDigi>
   <use name=root>
</library> 

<library file=stubs/EcalGraphDumperModule.cc name=EcalGraphDumperModule>
   <flags EDM_PLUGIN=1> 
   <use name=cppunit>
   <use name=root>
   <use name=DataFormats/EcalDigi>
</library> 

<library file=stubs/EcalPnGraphDumperModule.cc name=EcalPnGraphDumperModule>
   <flags EDM_PLUGIN=1>
   <use name=cppunit>
   <use name=root>
   <use name=DataFormats/EcalDigi>
</library>

#<bin name=testEcalUnpackingModule file=testRunner.cc,testEcalUnpackingModule.cc>
#   <use name=cppunit>
#</bin>
